### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by El3ctr1cR** [loomne/AutoJunk_cpp_csharp#3]
when i try to add the junk it doesn't add the junk it gives a weird code:

`<html>
<head>
<title>Free Web Hosting, Domain Hosting, Reliable Web Hosting Provider, Domain registration, Inexpensive, Low Cost, Affordable, Reseller Program, PHP, MySQL, Linux, Ecommerce</title>
<meta name="Description" content="Affordable, reliable web hosting and domain registration provider: low cost, inexpensive plans, reseller program, complete e-commerce solutions, instant customer support, PHP, MySQL, Linux, Perl, CGI.">
<meta name="Keywords" content="web,hosting,free,site,affordable,inexpensive,cheap,domain,name,registration,register,reseller,program,ftp,php,sql,mysql,database,cgi,perl,lamp,asp,ms,frontpage,server,net,ecommerce,services,business,email,page,unix,linux,company,virtual,internet,secure,registrar,the,best,low,cost,discount,e,commerce,solution,personal,professional,no ads,Support,cpanel,subdomains,dns,com,webpage,website,homepage,managed,zettahost,plans,file,jsp,unlimited,software,comparison,exchange,high,ratings,application,dollar,forum,board,blog,weblog,log,java,servlet,cam,list,packages,media,control,panel,prices,cheapest,for sale,isp,multimedia,resell,url,biz,registering,expired,tld,build,dynamic,who,own,domein,doman,icann,top,level,no ad,bannerless,urls,addresses,feature,domainname,reselling,nick,tlds,registrants,public,the,registry,buy,find,forwarding,trust,purchase,qualified,pro,get,renew,back,order,bulk,transfer,budget,design,sites,companies,plan,highest,rating,search,whois,registrations,partner,affiliate,Access,Data,Transfer,Disk,Space,POP3,mail,SMTP,Autoresponder,Aliasing,forward,Apache,phpMyAdmin,ssi,Side,Includes,Extensions,Online,statistics,24,7,fee,offer,org,biz,info,us,help,whois,trial,multiple,parking,check,top,ssl,options,bandwidth,band,GB,MB,Setup,Toll,HDD,industry,quality,lookup,uptime,Superb technical support and outstanding staff service,usa,new,ensim,plesk,shared,review,cold,fusion,image,video,music,photo,game,mp3,small,most,webcam,e-business">
<meta name="abstract" content="Web Hosting Services, Domain Name Registration, High Quality, Inexpensive Plans, Low Cost, Affordable, Reliable Provider, Reseller Program, Complete Ecommerce Solutions, Best Customer Support, PHP, MySQL, Linux, CGI, Perl, LAMP">
<meta name="Distribution" content="Global">
<meta name="Revisit" content="2 days">
<meta name="Language" content="EN">
<meta name="Robots" content="all">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta HTTP-EQUIV="REFRESH" content="1; url=http://host.atwebpages.com/">
<style type="text/css">
    
</style>
<script type="text/javascript">

</script>
</head>

<body bgcolor="#000000" marginwidth="0" marginheight="0" topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0">
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td valign="top">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>
            <table width="100%" cellpadding="0" cellspacing="1" border="0" class="header_table">
              <tr>
                
                <td bgcolor="#000000" align="center"><img src="overtraffic.jpg" width="187" height="20"></td>
                
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="15" style="margin-top: 10px">
        <tr>
          <td class="text">Notice: The website http://mangekyoukraken.mygamesonline.org is temporarily suspended due to overtraffic.</td>
        </tr>
        <tr>
          <td class="text_black">
            <font color="#ffffff"> <b>Description:</b> The allocated data traffic of the hosting account for this website has been exceeded and the website is temporarily suspended.
             
	     
             To view this website again you have the following options:
             
             <div style="padding-left: 15px"> <b>You are the owner of the hosting account?</b>
                <div style="padding-left: 30px">
                You can login your Hosting Control Panel and use the Upgrades section in order to purchase additional monthly data traffic for your website.
		Or you can wait till the beginning of the next month when the data traffic counters will be reset and your website will be visible online again.
                </div>
                 <b>You are a visitor?</b>
                <div style="padding-left: 30px">
                You can come back and visit this website in the begining of the next month when the allocated data traffic will be reset automatically. Then this
		website should be working again, unless something else happen to the website and its contents.
                </div>
             </div>
          </td>
        </tr>
      </table>
    </td>
  <tr>
  </table>

<script type="text/javascript">
var dc_UnitID = 14;
var dc_PublisherID = 33692;
var dc_AdLinkColor = 'blue';
var dc_isBoldActive= 'no';
var dc_adprod='ADL';
</script>
<script type="text/javascript" 
SRC="http://kona.kontera.com/javascript/lib/KonaLibInline.js"></script>

</body>
</html>`

**Comment by loomne** [comment]
I am SORRY! it is bescause of my hosting... Wait for 0.5.9 dev build 27, it will be released on 16.2.2018.
Or maybe today. With a beta C++ engine, working also offline.

**Comment by loomne** [comment]
FIXED! https://github.com/loomne/AutoJunk_cpp_csharp/releases/tag/0.5.9_DEVBUILD27
