### ISSUE TITLE
Plz release new version ;(

### ISSUE THREAD

**Issue by xkonfig** [loomne/AutoJunk_cpp_csharp#4]
Hey dude please release new version today i need this!

Good work!

**Comment by loomne** [comment]
Thank you! I Release it !!! i just right now testing a new junk code ! STAY here, i release it TODAY! 👯‍♂️

**Comment by loomne** [comment]
FIXED! https://github.com/loomne/AutoJunk_cpp_csharp/releases/tag/0.5.9_DEVBUILD27
