### ISSUE TITLE
SOLVED

### ISSUE THREAD

**Issue by ghost** [loomne/AutoJunk_cpp_csharp#5]
This is Malware dont download it.
If you start the .exe it will drop some files on c, run it and then delete it. It does that because its binded with a virus. If you run that shit reinstall windows and change all your passwords.

**Comment by loomne** [comment]
No it is not a malware... It is a source code protection.. This plugin will be opensource, if it is completed. Then you can take a look. But, i release source code today, with new version.. and then you see, it is not malware.. It executing windows CMD console, bescause it is console application. And however, no exe files are dropped to C. Only cmd is executed, but cmd is executed with every console application include java, c#,c++.
Yes. some antivirus write this: "Win32 packed virus" it is bescause it uses Enigma Protector (google it),
and this hiding the source code from decompiling.

**Comment by loomne** [comment]
And can you say me, why you think it is a malware? :)

**Comment by ghost** [comment]
https://www.hybrid-analysis.com/search?query=AutoJunk.exe
there are detailed reports about which files will be dropped and executed, which folders it access and other stuff like this

**Comment by loomne** [comment]
I say. It is bullshit what you send. It writes virus, bescause of source code protection called Enigma protector. It is not a virus, so dont be scared :)

**Comment by loomne** [comment]
Please, go here. http://enigmaprotector.com/

**Comment by ghost** [comment]
I know that you use a fucking protection against VMs, but i already tried it on a real system and look which files are modified and I'm 100% sure that it's malicious. You are just binded your RAT to that tool and thought that just using enigma would hide that.

**Comment by loomne** [comment]
No. Only binded file, is autojunkapi.dll.
This is the executed file, but nothing more.
You can decompile autojunkapi as well, you can found it in zip from new version.
For making own plugins, and engines..
If there is a rat, run program called WireShark, or other program which see, where is the application connecting.. if i using rat, you should see my ip adress.

**Comment by ghost** [comment]
Say goodbye to your github account

**Comment by loomne** [comment]
okay.. bye bye. I know, it is 100% without viruses. and i can give sourcecode, to everyone want it.. So that what you say, is not a problem for me :) if i have there virus, i simply delete your thread, to no one see it .. logic.
You just simple dont want to users download it, or you have no idea. 👎
