### ISSUE TITLE
version 0.57 was better

### ISSUE THREAD

**Issue by xkonfig** [loomne/AutoJunk_cpp_csharp#6]
Hey man 0.57 was better or whatever version you had that was generating junk like this: http://junkcode.gehaxelt.in/
It made the .dll's smaller in size for better optimization but this new one makes the size of the .dll's huge and doesn't create much difference for sigbenching :/

Thanks

**Comment by loomne** [comment]
I test it,
and with junkcode gehaxelt, is 35%.
http://prntscr.com/ig1a7x
With autojunk c++ engine, is 27%
http://prntscr.com/ig1aqy

I working on offline engine, same like that what you send.. Just wait for final version 0.5.9 please.
For now, stay and try to update to actual developer builds.
AutoJunk can delete old junk codes, so if i update it, autojunk automaticly delete the old (big junk code), and replace it with new like what you send.. I try to do it to developer build 30.

**Comment by loomne** [comment]
I am done! :) You can download AutoJunks brother KingJunk 0.5.7 known as AutoJunk 0.5.10 !
https://github.com/loomne/AutoJunk_cpp_csharp/releases/tag/0.5.10
